apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 60
commands:
  - script: |
      set -e
      priority=$(kubectl get pod priority-pod -n $NAMESPACE -o jsonpath='{.spec.priority}')
      test "$priority" -eq 1000
---
apiVersion: v1
kind: Pod
metadata:
  name: priority-pod
status:
  phase: Running
