apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 90
collectors:
  - type: pod
    selector: job-name=counter
    tail: 20
---
apiVersion: batch/v1
kind: Job
metadata:
  name: counter
status:
  succeeded: 1
