apiVersion: v1
kind: Pod
metadata:
  name: probe-exec
status:
  phase: Running
  containerStatuses:
  - ready: true
---
apiVersion: v1
kind: Pod
metadata:
  name: probe-http
status:
  phase: Running
  containerStatuses:
  - ready: true
    started: true
---
apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp
status:
  phase: Running
  containerStatuses:
  - ready: true
